Repository telekom/pubsub-horizon-go, pull requests merged in 2024-07, with the labels that each got.

#1 Allow creating caches from an existing client
  cache/cache.go
  cache/cache_test.go
  test/docker.go
Labels: enhancement

#2 Add cache entry listener
  cache/cache.go
  cache/cache_test.go
  cache/listener.go
  cache/listener_test.go
Labels: enhancement

#3 Introduce generic interfaces for caches
  cache/cache.go
  cache/hazelcast.go
  cache/hazelcast_test.go
Labels: enhancement

#6 Add fixed types to enums
  enum/circuit_breaker_status.go
  enum/delivery_type.go
  enum/responsefilter_mode.go
Labels: bug

#7 Add the event-type to the circuit-breaker message
  message/circuit_breaker_message.go
Labels: enhancement

#9 Add a custom timestamp type that enforces the RFC3339 format in JSON
  message/circuit_breaker_message.go
  types/timestamp.go
  types/timestamp_test.go
Labels: enhancement

#13 Add tracing wrapper for common use-cases
  .reuse/dep5
  REUSE.toml
  go.mod
  go.sum
  tracing/main_test.go
  tracing/tracing.go
  tracing/tracing_test.go
  tracing/util.go
  tracing/util_test.go
Labels: enhancement

#15 Update dockertest (v3.10.0) dependencies
  go.mod
  go.sum
Labels: dependencies
